export default {
    MOVIES_LIST_REQUEST : 'MOVIES_LIST_REQUEST',
    MOVIES_LIST_SUCCESS : 'MOVIES_LIST_SUCCESS',
    MOVIES_LIST_ERROR : 'MOVIES_LIST_ERROR',
    GET_MOVIE_REQUEST : 'GET_MOVIE_REQUEST',
    GET_MOVIE_SUCCESS : 'GET_MOVIE_SUCCESS',
    GET_MOVIE_ERROR : 'GET_MOVIE_ERROR',
    SEARCH_MOVIES_REQUEST : 'SEARCH_MOVIES_REQUEST',
    SEARCH_MOVIES_SUCCESS : 'SEARCH_MOVIES_SUCCESS',
    SEARCH_MOVIES_ERROR : 'SEARCH_MOVIES_ERROR',
}